(fix)Fixes jumping cursor issue
openmrs/openmrs-form-engine-lib pull request #147
Opened 2023-11-17 15:42 UTC by arodidev

## Requirements

- [x] This PR has a title that briefly describes the work done including the ticket number. If there is a ticket, make sure your PR title includes a [conventional commit](https://o3-dev.docs.openmrs.org/#/getting_started/contributing?id=your-pr-title-should-indicate-the-type-of-change-it-is) label. See existing PR titles for inspiration.
- [x] My work conforms to the [OpenMRS 3.0 Styleguide](https://om.rs/styleguide) and [design documentation](https://zeroheight.com/23a080e38/p/880723-introduction).
- [ ] My work includes tests or is validated by existing tests.

## Summary

## Screenshots

## Related Issue

## Other

2023-11-20 10:17 UTC, Herobiam approved these changes

2023-11-20 11:37 UTC, pirupius requested changes

2023-11-20 11:37 UTC, pirupius commented on src/api/types.ts
> +    isUnspecified?: Boolean,
```suggestion
    isUnspecified?: boolean,
```

2023-11-20 11:37 UTC, pirupius commented on src/components/encounter/ohri-encounter-form.component.tsx
> +    isUnspecified: Boolean,
```suggestion
    isUnspecified: boolean,
```

2023-11-21 05:24 UTC, pirupius approved these changes

2023-11-21 05:24 UTC, merged