(feat) O3-1987: Disable `multiCheckbox` input options given provided expression
openmrs/openmrs-form-engine-lib pull request #196
Opened 2024-04-22 12:44 UTC by usamaidrsk

## Requirements

- [ x ] This PR has a title that briefly describes the work done including the ticket number. If there is a ticket, make sure your PR title includes a [conventional commit](https://o3-dev.docs.openmrs.org/#/getting_started/contributing?id=your-pr-title-should-indicate-the-type-of-change-it-is) label. See existing PR titles for inspiration.
- [ ] My work conforms to the [OpenMRS 3.0 Styleguide](https://om.rs/styleguide) and [design documentation](https://zeroheight.com/23a080e38/p/880723-introduction).
- [ ] My work includes tests or is validated by existing tests.

## Summary

This PR adds that `multiCheckbox` options can be disabled given provided expressions.

This is example field to use in a schema
**Note**: | The regex example requires to disable the first answer option if the patient is not Female

```typescript
       {
              "label": "Was this visit scheduled?",
              "type": "obs",
              "required": false,
              "id": "scheduledVisit",
              "questionOptions": {
                "rendering": "multiCheckbox",
                "concept": "a89ff9a6-1350-11df-a1f1-0026b9348838",
                "answers": [
                  {
                    "concept": "a89b6440-1350-11df-a1f1-0026b9348838",
                    "label": "Scheduled visit",
                    "disable": {
                      "disableWhenExpression": "sex !== 'F'"
                    }
                  },
                  {
                    "concept": "a89ff816-1350-11df-a1f1-0026b9348838",
                    "label": "Unscheduled visit early"
                  },
                  {
                    "concept": "a89ff8de-1350-11df-a1f1-0026b9348838",
                    "label": "Unscheduled visit late"
                  }
                ]
              }
            },
``` 
## Screenshots

![image](https://github.com/openmrs/openmrs-form-engine-lib/assets/53287480/48ea7ab0-be8c-43a3-947c-62928fd839a9)

## Related Issue

[O3-1987](https://openmrs.atlassian.net/browse/O3-1987)

## Other

2024-04-22 22:37 UTC, samuelmale requested changes
@usamaidrsk did you see the failing tests?

2024-04-23 13:31 UTC, pirupius commented on src/components/encounter/ohri-encounter-form.component.tsx
> +                                                                      formSessionDate,
This needs to be formatted back. The changes are adding unnecessary tabs

2024-04-23 13:31 UTC, pirupius commented on src/components/encounter/ohri-encounter-form.component.tsx
> +  const {encounterRole} = useEncounterRole();
same applies here
```suggestion
  const { encounterRole } = useEncounterRole();
```

2024-04-23 13:31 UTC, pirupius commented on src/components/encounter/ohri-encounter-form.component.tsx
> +  const {initialValues: tempInitialValues, isBindingComplete} = useInitialValues(
Please confirm the the your lint settings to avoid unnecessary changes to files

2024-04-23 13:42 UTC, usamaidrsk commented on src/api/types.ts
> +  [key: string]: any
yes, there are usages of the predefined properties

2024-04-23 23:09 UTC, samuelmale reviewed
Looks good overall, just a few minor comments

2024-04-23 23:09 UTC, samuelmale commented on src/components/inputs/multi-select/ohri-multi-select-component.test.tsx
> +  it('calls onChange when selection changes', () => {
Can we have an actual test scenario where the disable property is updated?

2024-04-24 11:59 UTC, denniskigen commented on src/components/inputs/multi-select/ohri-multi-select-component.test.tsx
> +  });
```suggestion
it('calls onChange when selection changes', async () => {
  renderForm({});

  const combobox = await screen.findByRole('combobox', { name: /was this visit scheduled/i });
  await user.click(combobox);

  expect(screen.getByRole('option', { name: /^scheduled visit$/i })).toBeInTheDocument();
  expect(screen.getByRole('option', { name: /unscheduled visit early/i })).toBeInTheDocument();
  expect(screen.getByRole('option', { name: /unscheduled visit late/i })).toBeInTheDocument();

  expect(testProps.onChange).toHaveBeenCalledTimes(1);
  expect(testProps.onChange).toHaveBeenCalledWith('nhif', '', expect.any(Function), expect.any(Function));
});

it('checkbox option is disabled when disabledWhenExpression resolves to true and does not call onChange', async () => {
  renderForm({ scheduledVisit: '', nhif: '8b715fed-97f6-4e38-8f6a-c167a42f8923' });

  await user.click(screen.getByRole('combobox', { name: /patient covered by nhif/i }));
  await user.click(screen.getByRole('option', { name: /no/i }));
  await user.tab();
  await user.click(screen.getByRole('combobox', { name: /was this visit scheduled/i }));
});
```

2024-04-25 06:28 UTC, merged